export const cantonMap = {
  'zurich': 'ZH',
  'bern': 'BE',
  'lucerne': 'LU',
  'uri': 'UR',
  'schwyz': 'SZ',
  'obwalden': 'OW',
  'nidwalden': 'NW',
  'glarus': 'GL',
  'zug': 'ZG',
  'fribourg': 'FR',
  'solothurn': 'SO',
  'baselstadt': 'BS',
  'baselland': 'BL',
  'shaffhausen': 'SH',
  'appenzell': 'AI',
  'stgallen': 'SG',
  'graubunden': 'GR',
  'argau': 'AG',
  'thurgau': 'TG',
  'ticino': 'TI',
  'vaud': 'VD',
  'valais': 'VS',
  'neuchatel': 'NE',
  'geneva': 'GE',
  'jura': 'JU',
};
